import { context, failure, sameOrigin,safeFile } from '@/lib/server';
import { seed } from '@/lib/content';
export const dynamic='force-dynamic';
export async function GET(){try{const {user,db,admin}=await context();const rows=await db.prepare('SELECT * FROM records').all<any>();const items=new Map(seed.map(x=>[x.id,x]));for(const r of rows.results){if(r.kind==='mark'&&r.owner!==user.userId)continue;const item={...JSON.parse(r.data),id:r.id,kind:r.kind,parent:r.parent,owner:r.owner,created:r.created};items.set(r.id,item);}const all=[...items.values()];const counts:Record<string,number>={};for(const r of rows.results)if(r.kind==='confused')counts[r.parent]=(counts[r.parent]||0)+1;return Response.json({items:all.filter(x=>x.kind!=='confused').map(x=>x.kind==='reaction'?{...x,owner:undefined,mine:x.owner===user.userId}:x),confused:counts,myConfused:rows.results.filter(r=>r.kind==='confused'&&r.owner===user.userId).map(r=>r.parent),user:{id:user.userId,name:user.fullName||'Участник группы',admin}},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return failure(e);}}
export async function POST(req:Request){try{if(!sameOrigin(req))return Response.json({error:'Недопустимый источник запроса'},{status:403});const {user,db,admin}=await context();const b=await req.json() as any;const kinds=['lecture','comment','request','collection','mark','confused','reaction'];if(!kinds.includes(b.kind))return Response.json({error:'Некорректный тип'},{status:400});const parent=String(b.parent||'').slice(0,100);if(['lecture','collection'].includes(b.kind)&&!admin)return Response.json({error:'Публиковать материалы может только староста.'},{status:403});let id=typeof b.id==='string'&&b.id?b.id:crypto.randomUUID();let existing=await db.prepare('SELECT owner,kind,data FROM records WHERE id=?').bind(id).first<any>();const preset=seed.find(x=>x.id===id);if((existing&&existing.kind!==b.kind)||(preset&&preset.kind!==b.kind))return Response.json({error:'Некорректная запись'},{status:400});if(existing&&existing.owner!==user.userId&&!admin)return Response.json({error:'Нет доступа к редактированию'},{status:403});let data:any={};const str=(v:unknown,n=20000)=>typeof v==='string'?v.trim().slice(0,n):'';
if(b.kind==='lecture'){data={title:str(b.title,200),subject:str(b.subject,100),date:str(b.date,10),summary:str(b.summary),formula:str(b.formula,3000),questions:str(b.questions,3000),audio:safeFile(b.audio),photos:Array.isArray(b.photos)?b.photos.map(safeFile).filter(Boolean).slice(0,12):[],demo:false};if(!data.title||!data.summary||!data.subject||!/^\d{4}-\d{2}-\d{2}$/.test(data.date))return Response.json({error:'Заполните тему, предмет, дату и выжимку.'},{status:400});}
if(b.kind==='comment'){data={text:str(b.text,4000),name:user.fullName||'Участник группы',image:safeFile(b.image),meme:!!b.meme,replyTo:str(b.replyTo,100),time:Number.isFinite(b.time)&&b.time>=0?Math.min(b.time,86400):null};if(!parent||(!data.text&&!data.image))return Response.json({error:'Добавьте текст или фото.'},{status:400});}
if(b.kind==='request'){data={title:str(b.title,200),subject:str(b.subject,100),date:str(b.date,10),closed:!!b.closed,lectureId:str(b.lectureId,100)};if(!data.title)return Response.json({error:'Опишите материал.'},{status:400});if(data.closed&&!admin)return Response.json({error:'Запрос закрывает староста после публикации.'},{status:403});if(data.closed&&!data.lectureId)return Response.json({error:'Укажите опубликованную лекцию.'},{status:400});}
if(b.kind==='collection'){data={title:str(b.title,200),lectureIds:Array.isArray(b.lectureIds)?b.lectureIds.filter((x:any)=>typeof x==='string').slice(0,100):[],formula:str(b.formula,4000),questions:str(b.questions,4000)};if(!data.title||!data.lectureIds.length)return Response.json({error:'Добавьте название и хотя бы одну лекцию.'},{status:400});}
if(['mark','confused','reaction'].includes(b.kind)){if(!parent)return Response.json({error:'Не выбрана лекция или сообщение.'},{status:400});data={value:str(b.value,40)};id=[b.kind,user.userId,parent,b.kind==='reaction'?data.value:''].join(':');existing=await db.prepare('SELECT id FROM records WHERE id=?').bind(id).first();if(b.kind!=='mark'&&existing){await db.prepare('DELETE FROM records WHERE id=? AND owner=?').bind(id,user.userId).run();return Response.json({ok:true});}if(b.kind==='mark'&&!['done','repeat',''].includes(data.value))return Response.json({error:'Некорректная отметка'},{status:400});}
await db.prepare('INSERT INTO records(id,kind,owner,parent,data,created) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(id,b.kind,user.userId,parent,JSON.stringify(data),new Date().toISOString()).run();return Response.json({ok:true,id});}catch(e){return failure(e);}}
